name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install hugo
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.74.0/hugo_extended_0.74.0_Linux-64bit.tar.gz
          tar -xvf hugo_extended_0.74.0_Linux-64bit.tar.gz
          ./hugo version

      - name: Build the site
        run: |
          ./hugo
          rm hugo_0.55.6_Linux-64bit.tar.gz
          rm hugo

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv public/* .
          touch .nojekyll
          echo "astrodata.nyc" >> CNAME
          git add -f *
          git add .nojekyll
          git -c user.name='astrodatagroup-bot' -c user.email='foreman.mackey+astrodata@gmail.com' commit -m "updating website"
          git push -q -f https://astrodatagroup-bot:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
