name: Build Site
on:
  push:
    branches:    
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Install hugo
      run: |
        git submodule update --init --recursive
        wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
        tar -xvf hugo_0.55.6_Linux-64bit.tar.gz
        ./hugo version

    - name: Build the site
      run: |
        ./hugo
        rm hugo_0.55.6_Linux-64bit.tar.gz
        rm hugo

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
        mv public/* .
        touch .nojekyll
        echo "astrodata.nyc" >> CNAME
        git add -f *
        git -c user.name='astrodatagroup-bot' -c user.email='astrodatagroup-bot' commit -m "updating website"
        git push -q -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
